version: 1.0.{build}
image: Visual Studio 2019
build_script:
- ps: .\build.ps1 -t CI
artifacts:
- path: ./artifacts
  name: artifacts
- path: ./tests/Api.Http.IntegrationTests/TestResults
  name: test-results