name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Build Action
      working-directory: .
      run: build.ps1
      shell: pwsh
